// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: finance.proto

package finance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FinanceEngine_HealthCheck_FullMethodName                 = "/finance.FinanceEngine/HealthCheck"
	FinanceEngine_CreateTransaction_FullMethodName           = "/finance.FinanceEngine/CreateTransaction"
	FinanceEngine_GetBalance_FullMethodName                  = "/finance.FinanceEngine/GetBalance"
	FinanceEngine_GetAccountSummary_FullMethodName           = "/finance.FinanceEngine/GetAccountSummary"
	FinanceEngine_GetLedgerEntries_FullMethodName            = "/finance.FinanceEngine/GetLedgerEntries"
	FinanceEngine_GetUserTotalCredit_FullMethodName          = "/finance.FinanceEngine/GetUserTotalCredit"
	FinanceEngine_GetUserTotalDebit_FullMethodName           = "/finance.FinanceEngine/GetUserTotalDebit"
	FinanceEngine_GetUserTotalBalance_FullMethodName         = "/finance.FinanceEngine/GetUserTotalBalance"
	FinanceEngine_CreateCreditCard_FullMethodName            = "/finance.FinanceEngine/CreateCreditCard"
	FinanceEngine_RecordCreditCardTransaction_FullMethodName = "/finance.FinanceEngine/RecordCreditCardTransaction"
	FinanceEngine_PayCreditCardStatement_FullMethodName      = "/finance.FinanceEngine/PayCreditCardStatement"
	FinanceEngine_GetCreditCardStatement_FullMethodName      = "/finance.FinanceEngine/GetCreditCardStatement"
)

// FinanceEngineClient is the client API for FinanceEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinanceEngineClient interface {
	// Health
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Ledger
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	GetAccountSummary(ctx context.Context, in *GetAccountSummaryRequest, opts ...grpc.CallOption) (*GetAccountSummaryResponse, error)
	GetLedgerEntries(ctx context.Context, in *GetLedgerEntriesRequest, opts ...grpc.CallOption) (*GetLedgerEntriesResponse, error)
	GetUserTotalCredit(ctx context.Context, in *GetUserTotalRequest, opts ...grpc.CallOption) (*GetUserTotalResponse, error)
	GetUserTotalDebit(ctx context.Context, in *GetUserTotalRequest, opts ...grpc.CallOption) (*GetUserTotalResponse, error)
	GetUserTotalBalance(ctx context.Context, in *GetUserTotalRequest, opts ...grpc.CallOption) (*GetUserTotalResponse, error)
	CreateCreditCard(ctx context.Context, in *CreateCreditCardRequest, opts ...grpc.CallOption) (*CreateCreditCardResponse, error)
	RecordCreditCardTransaction(ctx context.Context, in *RecordCreditCardTransactionRequest, opts ...grpc.CallOption) (*RecordCreditCardTransactionResponse, error)
	PayCreditCardStatement(ctx context.Context, in *PayCreditCardStatementRequest, opts ...grpc.CallOption) (*PayCreditCardStatementResponse, error)
	GetCreditCardStatement(ctx context.Context, in *GetCreditCardStatementRequest, opts ...grpc.CallOption) (*GetCreditCardStatementResponse, error)
}

type financeEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanceEngineClient(cc grpc.ClientConnInterface) FinanceEngineClient {
	return &financeEngineClient{cc}
}

func (c *financeEngineClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTransactionResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_CreateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) GetAccountSummary(ctx context.Context, in *GetAccountSummaryRequest, opts ...grpc.CallOption) (*GetAccountSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountSummaryResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_GetAccountSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) GetLedgerEntries(ctx context.Context, in *GetLedgerEntriesRequest, opts ...grpc.CallOption) (*GetLedgerEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLedgerEntriesResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_GetLedgerEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) GetUserTotalCredit(ctx context.Context, in *GetUserTotalRequest, opts ...grpc.CallOption) (*GetUserTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTotalResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_GetUserTotalCredit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) GetUserTotalDebit(ctx context.Context, in *GetUserTotalRequest, opts ...grpc.CallOption) (*GetUserTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTotalResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_GetUserTotalDebit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) GetUserTotalBalance(ctx context.Context, in *GetUserTotalRequest, opts ...grpc.CallOption) (*GetUserTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTotalResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_GetUserTotalBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) CreateCreditCard(ctx context.Context, in *CreateCreditCardRequest, opts ...grpc.CallOption) (*CreateCreditCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCreditCardResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_CreateCreditCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) RecordCreditCardTransaction(ctx context.Context, in *RecordCreditCardTransactionRequest, opts ...grpc.CallOption) (*RecordCreditCardTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordCreditCardTransactionResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_RecordCreditCardTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) PayCreditCardStatement(ctx context.Context, in *PayCreditCardStatementRequest, opts ...grpc.CallOption) (*PayCreditCardStatementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayCreditCardStatementResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_PayCreditCardStatement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeEngineClient) GetCreditCardStatement(ctx context.Context, in *GetCreditCardStatementRequest, opts ...grpc.CallOption) (*GetCreditCardStatementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCreditCardStatementResponse)
	err := c.cc.Invoke(ctx, FinanceEngine_GetCreditCardStatement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceEngineServer is the server API for FinanceEngine service.
// All implementations must embed UnimplementedFinanceEngineServer
// for forward compatibility.
type FinanceEngineServer interface {
	// Health
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	// Ledger
	CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	GetAccountSummary(context.Context, *GetAccountSummaryRequest) (*GetAccountSummaryResponse, error)
	GetLedgerEntries(context.Context, *GetLedgerEntriesRequest) (*GetLedgerEntriesResponse, error)
	GetUserTotalCredit(context.Context, *GetUserTotalRequest) (*GetUserTotalResponse, error)
	GetUserTotalDebit(context.Context, *GetUserTotalRequest) (*GetUserTotalResponse, error)
	GetUserTotalBalance(context.Context, *GetUserTotalRequest) (*GetUserTotalResponse, error)
	CreateCreditCard(context.Context, *CreateCreditCardRequest) (*CreateCreditCardResponse, error)
	RecordCreditCardTransaction(context.Context, *RecordCreditCardTransactionRequest) (*RecordCreditCardTransactionResponse, error)
	PayCreditCardStatement(context.Context, *PayCreditCardStatementRequest) (*PayCreditCardStatementResponse, error)
	GetCreditCardStatement(context.Context, *GetCreditCardStatementRequest) (*GetCreditCardStatementResponse, error)
	mustEmbedUnimplementedFinanceEngineServer()
}

// UnimplementedFinanceEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinanceEngineServer struct{}

func (UnimplementedFinanceEngineServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedFinanceEngineServer) CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedFinanceEngineServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedFinanceEngineServer) GetAccountSummary(context.Context, *GetAccountSummaryRequest) (*GetAccountSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountSummary not implemented")
}
func (UnimplementedFinanceEngineServer) GetLedgerEntries(context.Context, *GetLedgerEntriesRequest) (*GetLedgerEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerEntries not implemented")
}
func (UnimplementedFinanceEngineServer) GetUserTotalCredit(context.Context, *GetUserTotalRequest) (*GetUserTotalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTotalCredit not implemented")
}
func (UnimplementedFinanceEngineServer) GetUserTotalDebit(context.Context, *GetUserTotalRequest) (*GetUserTotalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTotalDebit not implemented")
}
func (UnimplementedFinanceEngineServer) GetUserTotalBalance(context.Context, *GetUserTotalRequest) (*GetUserTotalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTotalBalance not implemented")
}
func (UnimplementedFinanceEngineServer) CreateCreditCard(context.Context, *CreateCreditCardRequest) (*CreateCreditCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCreditCard not implemented")
}
func (UnimplementedFinanceEngineServer) RecordCreditCardTransaction(context.Context, *RecordCreditCardTransactionRequest) (*RecordCreditCardTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordCreditCardTransaction not implemented")
}
func (UnimplementedFinanceEngineServer) PayCreditCardStatement(context.Context, *PayCreditCardStatementRequest) (*PayCreditCardStatementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayCreditCardStatement not implemented")
}
func (UnimplementedFinanceEngineServer) GetCreditCardStatement(context.Context, *GetCreditCardStatementRequest) (*GetCreditCardStatementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCreditCardStatement not implemented")
}
func (UnimplementedFinanceEngineServer) mustEmbedUnimplementedFinanceEngineServer() {}
func (UnimplementedFinanceEngineServer) testEmbeddedByValue()                       {}

// UnsafeFinanceEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinanceEngineServer will
// result in compilation errors.
type UnsafeFinanceEngineServer interface {
	mustEmbedUnimplementedFinanceEngineServer()
}

func RegisterFinanceEngineServer(s grpc.ServiceRegistrar, srv FinanceEngineServer) {
	// If the following call panics, it indicates UnimplementedFinanceEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FinanceEngine_ServiceDesc, srv)
}

func _FinanceEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_CreateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_GetAccountSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).GetAccountSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_GetAccountSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).GetAccountSummary(ctx, req.(*GetAccountSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_GetLedgerEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).GetLedgerEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_GetLedgerEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).GetLedgerEntries(ctx, req.(*GetLedgerEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_GetUserTotalCredit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).GetUserTotalCredit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_GetUserTotalCredit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).GetUserTotalCredit(ctx, req.(*GetUserTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_GetUserTotalDebit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).GetUserTotalDebit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_GetUserTotalDebit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).GetUserTotalDebit(ctx, req.(*GetUserTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_GetUserTotalBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).GetUserTotalBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_GetUserTotalBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).GetUserTotalBalance(ctx, req.(*GetUserTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_CreateCreditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCreditCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).CreateCreditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_CreateCreditCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).CreateCreditCard(ctx, req.(*CreateCreditCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_RecordCreditCardTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordCreditCardTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).RecordCreditCardTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_RecordCreditCardTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).RecordCreditCardTransaction(ctx, req.(*RecordCreditCardTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_PayCreditCardStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayCreditCardStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).PayCreditCardStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_PayCreditCardStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).PayCreditCardStatement(ctx, req.(*PayCreditCardStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceEngine_GetCreditCardStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCreditCardStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceEngineServer).GetCreditCardStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceEngine_GetCreditCardStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceEngineServer).GetCreditCardStatement(ctx, req.(*GetCreditCardStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinanceEngine_ServiceDesc is the grpc.ServiceDesc for FinanceEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinanceEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finance.FinanceEngine",
	HandlerType: (*FinanceEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _FinanceEngine_HealthCheck_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _FinanceEngine_CreateTransaction_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _FinanceEngine_GetBalance_Handler,
		},
		{
			MethodName: "GetAccountSummary",
			Handler:    _FinanceEngine_GetAccountSummary_Handler,
		},
		{
			MethodName: "GetLedgerEntries",
			Handler:    _FinanceEngine_GetLedgerEntries_Handler,
		},
		{
			MethodName: "GetUserTotalCredit",
			Handler:    _FinanceEngine_GetUserTotalCredit_Handler,
		},
		{
			MethodName: "GetUserTotalDebit",
			Handler:    _FinanceEngine_GetUserTotalDebit_Handler,
		},
		{
			MethodName: "GetUserTotalBalance",
			Handler:    _FinanceEngine_GetUserTotalBalance_Handler,
		},
		{
			MethodName: "CreateCreditCard",
			Handler:    _FinanceEngine_CreateCreditCard_Handler,
		},
		{
			MethodName: "RecordCreditCardTransaction",
			Handler:    _FinanceEngine_RecordCreditCardTransaction_Handler,
		},
		{
			MethodName: "PayCreditCardStatement",
			Handler:    _FinanceEngine_PayCreditCardStatement_Handler,
		},
		{
			MethodName: "GetCreditCardStatement",
			Handler:    _FinanceEngine_GetCreditCardStatement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finance.proto",
}
