// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: finance.proto

package finance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTransactionRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{4}
}

func (x *Entry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Entry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Entry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{6}
}

func (x *GetBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type GetAccountSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSummaryRequest) Reset() {
	*x = GetAccountSummaryRequest{}
	mi := &file_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSummaryRequest) ProtoMessage() {}

func (x *GetAccountSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetAccountSummaryRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountSummaryRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Balance       string                 `protobuf:"bytes,4,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSummaryResponse) Reset() {
	*x = GetAccountSummaryResponse{}
	mi := &file_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSummaryResponse) ProtoMessage() {}

func (x *GetAccountSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetAccountSummaryResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccountSummaryResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountSummaryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAccountSummaryResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetAccountSummaryResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetAccountSummaryResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetLedgerEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerEntriesRequest) Reset() {
	*x = GetLedgerEntriesRequest{}
	mi := &file_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerEntriesRequest) ProtoMessage() {}

func (x *GetLedgerEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerEntriesRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{9}
}

func (x *GetLedgerEntriesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetLedgerEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerEntriesResponse) Reset() {
	*x = GetLedgerEntriesResponse{}
	mi := &file_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerEntriesResponse) ProtoMessage() {}

func (x *GetLedgerEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerEntriesResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{10}
}

func (x *GetLedgerEntriesResponse) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{11}
}

func (x *LedgerEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *LedgerEntry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LedgerEntry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *LedgerEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LedgerEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LedgerEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetUserTotalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTotalRequest) Reset() {
	*x = GetUserTotalRequest{}
	mi := &file_finance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTotalRequest) ProtoMessage() {}

func (x *GetUserTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTotalRequest.ProtoReflect.Descriptor instead.
func (*GetUserTotalRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserTotalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalCredit   string                 `protobuf:"bytes,2,opt,name=total_credit,json=totalCredit,proto3" json:"total_credit,omitempty"`
	TotalDebit    string                 `protobuf:"bytes,3,opt,name=total_debit,json=totalDebit,proto3" json:"total_debit,omitempty"`
	TotalBalance  string                 `protobuf:"bytes,4,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTotalResponse) Reset() {
	*x = GetUserTotalResponse{}
	mi := &file_finance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTotalResponse) ProtoMessage() {}

func (x *GetUserTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTotalResponse.ProtoReflect.Descriptor instead.
func (*GetUserTotalResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserTotalResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserTotalResponse) GetTotalCredit() string {
	if x != nil {
		return x.TotalCredit
	}
	return ""
}

func (x *GetUserTotalResponse) GetTotalDebit() string {
	if x != nil {
		return x.TotalDebit
	}
	return ""
}

func (x *GetUserTotalResponse) GetTotalBalance() string {
	if x != nil {
		return x.TotalBalance
	}
	return ""
}

type CreateCreditCardRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CreditLimit    string                 `protobuf:"bytes,2,opt,name=credit_limit,json=creditLimit,proto3" json:"credit_limit,omitempty"`
	BillingDay     int32                  `protobuf:"varint,3,opt,name=billing_day,json=billingDay,proto3" json:"billing_day,omitempty"`
	PaymentDueDays int32                  `protobuf:"varint,4,opt,name=payment_due_days,json=paymentDueDays,proto3" json:"payment_due_days,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCreditCardRequest) Reset() {
	*x = CreateCreditCardRequest{}
	mi := &file_finance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCreditCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCreditCardRequest) ProtoMessage() {}

func (x *CreateCreditCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCreditCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCreditCardRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCreditCardRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateCreditCardRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *CreateCreditCardRequest) GetBillingDay() int32 {
	if x != nil {
		return x.BillingDay
	}
	return 0
}

func (x *CreateCreditCardRequest) GetPaymentDueDays() int32 {
	if x != nil {
		return x.PaymentDueDays
	}
	return 0
}

type CreateCreditCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditCardId  string                 `protobuf:"bytes,1,opt,name=credit_card_id,json=creditCardId,proto3" json:"credit_card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCreditCardResponse) Reset() {
	*x = CreateCreditCardResponse{}
	mi := &file_finance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCreditCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCreditCardResponse) ProtoMessage() {}

func (x *CreateCreditCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCreditCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCreditCardResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCreditCardResponse) GetCreditCardId() string {
	if x != nil {
		return x.CreditCardId
	}
	return ""
}

type RecordCreditCardTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PurchaseDate  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=purchase_date,json=purchaseDate,proto3" json:"purchase_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordCreditCardTransactionRequest) Reset() {
	*x = RecordCreditCardTransactionRequest{}
	mi := &file_finance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordCreditCardTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCreditCardTransactionRequest) ProtoMessage() {}

func (x *RecordCreditCardTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCreditCardTransactionRequest.ProtoReflect.Descriptor instead.
func (*RecordCreditCardTransactionRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{16}
}

func (x *RecordCreditCardTransactionRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *RecordCreditCardTransactionRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RecordCreditCardTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecordCreditCardTransactionRequest) GetPurchaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PurchaseDate
	}
	return nil
}

type RecordCreditCardTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordCreditCardTransactionResponse) Reset() {
	*x = RecordCreditCardTransactionResponse{}
	mi := &file_finance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordCreditCardTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCreditCardTransactionResponse) ProtoMessage() {}

func (x *RecordCreditCardTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCreditCardTransactionResponse.ProtoReflect.Descriptor instead.
func (*RecordCreditCardTransactionResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{17}
}

func (x *RecordCreditCardTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type PayCreditCardStatementRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StatementId      string                 `protobuf:"bytes,1,opt,name=statement_id,json=statementId,proto3" json:"statement_id,omitempty"`
	CardId           string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	PaymentAccountId string                 `protobuf:"bytes,3,opt,name=payment_account_id,json=paymentAccountId,proto3" json:"payment_account_id,omitempty"`
	Amount           string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PayCreditCardStatementRequest) Reset() {
	*x = PayCreditCardStatementRequest{}
	mi := &file_finance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCreditCardStatementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCreditCardStatementRequest) ProtoMessage() {}

func (x *PayCreditCardStatementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCreditCardStatementRequest.ProtoReflect.Descriptor instead.
func (*PayCreditCardStatementRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{18}
}

func (x *PayCreditCardStatementRequest) GetStatementId() string {
	if x != nil {
		return x.StatementId
	}
	return ""
}

func (x *PayCreditCardStatementRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *PayCreditCardStatementRequest) GetPaymentAccountId() string {
	if x != nil {
		return x.PaymentAccountId
	}
	return ""
}

func (x *PayCreditCardStatementRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PayCreditCardStatementRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PayCreditCardStatementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCreditCardStatementResponse) Reset() {
	*x = PayCreditCardStatementResponse{}
	mi := &file_finance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCreditCardStatementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCreditCardStatementResponse) ProtoMessage() {}

func (x *PayCreditCardStatementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCreditCardStatementResponse.ProtoReflect.Descriptor instead.
func (*PayCreditCardStatementResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{19}
}

func (x *PayCreditCardStatementResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetCreditCardStatementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatementId   string                 `protobuf:"bytes,1,opt,name=statement_id,json=statementId,proto3" json:"statement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreditCardStatementRequest) Reset() {
	*x = GetCreditCardStatementRequest{}
	mi := &file_finance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreditCardStatementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditCardStatementRequest) ProtoMessage() {}

func (x *GetCreditCardStatementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditCardStatementRequest.ProtoReflect.Descriptor instead.
func (*GetCreditCardStatementRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{20}
}

func (x *GetCreditCardStatementRequest) GetStatementId() string {
	if x != nil {
		return x.StatementId
	}
	return ""
}

type GetCreditCardStatementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatementId   string                 `protobuf:"bytes,1,opt,name=statement_id,json=statementId,proto3" json:"statement_id,omitempty"`
	CreditCardId  string                 `protobuf:"bytes,2,opt,name=credit_card_id,json=creditCardId,proto3" json:"credit_card_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	StatementDate string                 `protobuf:"bytes,5,opt,name=statement_date,json=statementDate,proto3" json:"statement_date,omitempty"`
	DueDate       string                 `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreditCardStatementResponse) Reset() {
	*x = GetCreditCardStatementResponse{}
	mi := &file_finance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreditCardStatementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditCardStatementResponse) ProtoMessage() {}

func (x *GetCreditCardStatementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditCardStatementResponse.ProtoReflect.Descriptor instead.
func (*GetCreditCardStatementResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{21}
}

func (x *GetCreditCardStatementResponse) GetStatementId() string {
	if x != nil {
		return x.StatementId
	}
	return ""
}

func (x *GetCreditCardStatementResponse) GetCreditCardId() string {
	if x != nil {
		return x.CreditCardId
	}
	return ""
}

func (x *GetCreditCardStatementResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetCreditCardStatementResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetCreditCardStatementResponse) GetStatementDate() string {
	if x != nil {
		return x.StatementDate
	}
	return ""
}

func (x *GetCreditCardStatementResponse) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *GetCreditCardStatementResponse) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *GetCreditCardStatementResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_finance_proto protoreflect.FileDescriptor

const file_finance_proto_rawDesc = "" +
	"\n" +
	"\rfinance.proto\x12\afinance\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"f\n" +
	"\x18CreateTransactionRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12(\n" +
	"\aentries\x18\x02 \x03(\v2\x0e.finance.EntryR\aentries\"B\n" +
	"\x19CreateTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"R\n" +
	"\x05Entry\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance\"9\n" +
	"\x18GetAccountSummaryRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x9b\x01\n" +
	"\x19GetAccountSummaryResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\abalance\x18\x04 \x01(\tR\abalance\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"8\n" +
	"\x17GetLedgerEntriesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"J\n" +
	"\x18GetLedgerEntriesResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.finance.LedgerEntryR\aentries\"\xc0\x01\n" +
	"\vLedgerEntry\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\".\n" +
	"\x13GetUserTotalRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x98\x01\n" +
	"\x14GetUserTotalResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\ftotal_credit\x18\x02 \x01(\tR\vtotalCredit\x12\x1f\n" +
	"\vtotal_debit\x18\x03 \x01(\tR\n" +
	"totalDebit\x12#\n" +
	"\rtotal_balance\x18\x04 \x01(\tR\ftotalBalance\"\xa6\x01\n" +
	"\x17CreateCreditCardRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\fcredit_limit\x18\x02 \x01(\tR\vcreditLimit\x12\x1f\n" +
	"\vbilling_day\x18\x03 \x01(\x05R\n" +
	"billingDay\x12(\n" +
	"\x10payment_due_days\x18\x04 \x01(\x05R\x0epaymentDueDays\"@\n" +
	"\x18CreateCreditCardResponse\x12$\n" +
	"\x0ecredit_card_id\x18\x01 \x01(\tR\fcreditCardId\"\xb8\x01\n" +
	"\"RecordCreditCardTransactionRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\rpurchase_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fpurchaseDate\"L\n" +
	"#RecordCreditCardTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\xc3\x01\n" +
	"\x1dPayCreditCardStatementRequest\x12!\n" +
	"\fstatement_id\x18\x01 \x01(\tR\vstatementId\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12,\n" +
	"\x12payment_account_id\x18\x03 \x01(\tR\x10paymentAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"G\n" +
	"\x1ePayCreditCardStatementResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"B\n" +
	"\x1dGetCreditCardStatementRequest\x12!\n" +
	"\fstatement_id\x18\x01 \x01(\tR\vstatementId\"\xa0\x02\n" +
	"\x1eGetCreditCardStatementResponse\x12!\n" +
	"\fstatement_id\x18\x01 \x01(\tR\vstatementId\x12$\n" +
	"\x0ecredit_card_id\x18\x02 \x01(\tR\fcreditCardId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12%\n" +
	"\x0estatement_date\x18\x05 \x01(\tR\rstatementDate\x12\x19\n" +
	"\bdue_date\x18\x06 \x01(\tR\adueDate\x12!\n" +
	"\ftotal_amount\x18\a \x01(\tR\vtotalAmount\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status2\xc9\b\n" +
	"\rFinanceEngine\x12>\n" +
	"\vHealthCheck\x12\x16.finance.HealthRequest\x1a\x17.finance.HealthResponse\x12Z\n" +
	"\x11CreateTransaction\x12!.finance.CreateTransactionRequest\x1a\".finance.CreateTransactionResponse\x12E\n" +
	"\n" +
	"GetBalance\x12\x1a.finance.GetBalanceRequest\x1a\x1b.finance.GetBalanceResponse\x12Z\n" +
	"\x11GetAccountSummary\x12!.finance.GetAccountSummaryRequest\x1a\".finance.GetAccountSummaryResponse\x12W\n" +
	"\x10GetLedgerEntries\x12 .finance.GetLedgerEntriesRequest\x1a!.finance.GetLedgerEntriesResponse\x12Q\n" +
	"\x12GetUserTotalCredit\x12\x1c.finance.GetUserTotalRequest\x1a\x1d.finance.GetUserTotalResponse\x12P\n" +
	"\x11GetUserTotalDebit\x12\x1c.finance.GetUserTotalRequest\x1a\x1d.finance.GetUserTotalResponse\x12R\n" +
	"\x13GetUserTotalBalance\x12\x1c.finance.GetUserTotalRequest\x1a\x1d.finance.GetUserTotalResponse\x12W\n" +
	"\x10CreateCreditCard\x12 .finance.CreateCreditCardRequest\x1a!.finance.CreateCreditCardResponse\x12x\n" +
	"\x1bRecordCreditCardTransaction\x12+.finance.RecordCreditCardTransactionRequest\x1a,.finance.RecordCreditCardTransactionResponse\x12i\n" +
	"\x16PayCreditCardStatement\x12&.finance.PayCreditCardStatementRequest\x1a'.finance.PayCreditCardStatementResponse\x12i\n" +
	"\x16GetCreditCardStatement\x12&.finance.GetCreditCardStatementRequest\x1a'.finance.GetCreditCardStatementResponseBV\n" +
	"\x18com.finankal.api.financeB\rFinanceProtosZ+github.com/kaloy/finankal/engine-go/financeb\x06proto3"

var (
	file_finance_proto_rawDescOnce sync.Once
	file_finance_proto_rawDescData []byte
)

func file_finance_proto_rawDescGZIP() []byte {
	file_finance_proto_rawDescOnce.Do(func() {
		file_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)))
	})
	return file_finance_proto_rawDescData
}

var file_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_finance_proto_goTypes = []any{
	(*HealthRequest)(nil),                       // 0: finance.HealthRequest
	(*HealthResponse)(nil),                      // 1: finance.HealthResponse
	(*CreateTransactionRequest)(nil),            // 2: finance.CreateTransactionRequest
	(*CreateTransactionResponse)(nil),           // 3: finance.CreateTransactionResponse
	(*Entry)(nil),                               // 4: finance.Entry
	(*GetBalanceRequest)(nil),                   // 5: finance.GetBalanceRequest
	(*GetBalanceResponse)(nil),                  // 6: finance.GetBalanceResponse
	(*GetAccountSummaryRequest)(nil),            // 7: finance.GetAccountSummaryRequest
	(*GetAccountSummaryResponse)(nil),           // 8: finance.GetAccountSummaryResponse
	(*GetLedgerEntriesRequest)(nil),             // 9: finance.GetLedgerEntriesRequest
	(*GetLedgerEntriesResponse)(nil),            // 10: finance.GetLedgerEntriesResponse
	(*LedgerEntry)(nil),                         // 11: finance.LedgerEntry
	(*GetUserTotalRequest)(nil),                 // 12: finance.GetUserTotalRequest
	(*GetUserTotalResponse)(nil),                // 13: finance.GetUserTotalResponse
	(*CreateCreditCardRequest)(nil),             // 14: finance.CreateCreditCardRequest
	(*CreateCreditCardResponse)(nil),            // 15: finance.CreateCreditCardResponse
	(*RecordCreditCardTransactionRequest)(nil),  // 16: finance.RecordCreditCardTransactionRequest
	(*RecordCreditCardTransactionResponse)(nil), // 17: finance.RecordCreditCardTransactionResponse
	(*PayCreditCardStatementRequest)(nil),       // 18: finance.PayCreditCardStatementRequest
	(*PayCreditCardStatementResponse)(nil),      // 19: finance.PayCreditCardStatementResponse
	(*GetCreditCardStatementRequest)(nil),       // 20: finance.GetCreditCardStatementRequest
	(*GetCreditCardStatementResponse)(nil),      // 21: finance.GetCreditCardStatementResponse
	(*timestamppb.Timestamp)(nil),               // 22: google.protobuf.Timestamp
}
var file_finance_proto_depIdxs = []int32{
	4,  // 0: finance.CreateTransactionRequest.entries:type_name -> finance.Entry
	11, // 1: finance.GetLedgerEntriesResponse.entries:type_name -> finance.LedgerEntry
	22, // 2: finance.RecordCreditCardTransactionRequest.purchase_date:type_name -> google.protobuf.Timestamp
	0,  // 3: finance.FinanceEngine.HealthCheck:input_type -> finance.HealthRequest
	2,  // 4: finance.FinanceEngine.CreateTransaction:input_type -> finance.CreateTransactionRequest
	5,  // 5: finance.FinanceEngine.GetBalance:input_type -> finance.GetBalanceRequest
	7,  // 6: finance.FinanceEngine.GetAccountSummary:input_type -> finance.GetAccountSummaryRequest
	9,  // 7: finance.FinanceEngine.GetLedgerEntries:input_type -> finance.GetLedgerEntriesRequest
	12, // 8: finance.FinanceEngine.GetUserTotalCredit:input_type -> finance.GetUserTotalRequest
	12, // 9: finance.FinanceEngine.GetUserTotalDebit:input_type -> finance.GetUserTotalRequest
	12, // 10: finance.FinanceEngine.GetUserTotalBalance:input_type -> finance.GetUserTotalRequest
	14, // 11: finance.FinanceEngine.CreateCreditCard:input_type -> finance.CreateCreditCardRequest
	16, // 12: finance.FinanceEngine.RecordCreditCardTransaction:input_type -> finance.RecordCreditCardTransactionRequest
	18, // 13: finance.FinanceEngine.PayCreditCardStatement:input_type -> finance.PayCreditCardStatementRequest
	20, // 14: finance.FinanceEngine.GetCreditCardStatement:input_type -> finance.GetCreditCardStatementRequest
	1,  // 15: finance.FinanceEngine.HealthCheck:output_type -> finance.HealthResponse
	3,  // 16: finance.FinanceEngine.CreateTransaction:output_type -> finance.CreateTransactionResponse
	6,  // 17: finance.FinanceEngine.GetBalance:output_type -> finance.GetBalanceResponse
	8,  // 18: finance.FinanceEngine.GetAccountSummary:output_type -> finance.GetAccountSummaryResponse
	10, // 19: finance.FinanceEngine.GetLedgerEntries:output_type -> finance.GetLedgerEntriesResponse
	13, // 20: finance.FinanceEngine.GetUserTotalCredit:output_type -> finance.GetUserTotalResponse
	13, // 21: finance.FinanceEngine.GetUserTotalDebit:output_type -> finance.GetUserTotalResponse
	13, // 22: finance.FinanceEngine.GetUserTotalBalance:output_type -> finance.GetUserTotalResponse
	15, // 23: finance.FinanceEngine.CreateCreditCard:output_type -> finance.CreateCreditCardResponse
	17, // 24: finance.FinanceEngine.RecordCreditCardTransaction:output_type -> finance.RecordCreditCardTransactionResponse
	19, // 25: finance.FinanceEngine.PayCreditCardStatement:output_type -> finance.PayCreditCardStatementResponse
	21, // 26: finance.FinanceEngine.GetCreditCardStatement:output_type -> finance.GetCreditCardStatementResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_finance_proto_init() }
func file_finance_proto_init() {
	if File_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_proto_goTypes,
		DependencyIndexes: file_finance_proto_depIdxs,
		MessageInfos:      file_finance_proto_msgTypes,
	}.Build()
	File_finance_proto = out.File
	file_finance_proto_goTypes = nil
	file_finance_proto_depIdxs = nil
}
